root = "."
tmp_dir = "tmp"

[build]
cmd = "make build"
bin = "build/npn"
full_bin = "./build/npn -v"
include_dir = []
include_ext = ["go", "html", "sql", "mod"]
exclude_dir = ["client", "build", "vendor", "gen", "npntemplate/gen", "projects"]
exclude_file = []
delay = 1000 # ms
stop_on_error = true
log = "air_errors.log"

[log]
time = true
